# curl -i http://httpbin.org/ip
GET {{baseUrl}}/orders
###
POST {{baseUrl}}/orders
Content-Type: application/json

{
  "OrderNumber": 4002,
  "CustomerName": "Order 2",
  "ProductName": "Order Description",
  "Quantity": 88,
  "OrderLines": [
        {
        "LineNumber": 1,
        "Product": "A",
        "Quantity": 1
        },
        {
        "LineNumber": 2,
        "Product": "B",
        "Quantity": 2
        }
    ]
}
###

DELETE {{baseUrl}}/orders/4002

###
GET {{baseUrl}}/orders/1007
###

PUT {{baseUrl}}/orders/1006
Content-Type: application/json

{
  "OrderNumber": 1006,
  "CustomerName": "Order 99",
  "ProductName": "Order 99 description",
  "Quantity": 99
}
###


