# curl -i http://httpbin.org/ip
GET {{baseUrl}}/orders
###
POST {{baseUrl}}/orders
Content-Type: application/json

{
  "orderNumber": 4002,
  "customerName": "Skuirrel Trading",
  "productName": "Order Description",
  "orderLines": [
    {
      "lineNumber": 12,
      "product": "A",
      "quantity": 1,
      "weight": {
        "value": 2,
        "type": "Kg"
      },
      "volume": {
        "value": 3,
        "type": "M3"
      }
    },
    {
      "lineNumber": 23,
      "product": "B",
      "quantity": 2,
      "weight": null,
      "volume": null
    }
  ],
  "customFields": [
    {
      "name": "Warranty",
      "value": "3",
      "type": "Integer",
      "createdDateTime": "0001-01-01T00:00:00",
      "updatedDateTime": null
    }
  ],
  "state": 1,
  "stateName": "New",
  "createdDateTime": "2024-08-17T10:12:12.712535Z",
  "updatedDateTime": "2024-08-17T10:12:12.712535Z",
  "totalQuantity": 3
}
###

DELETE {{baseUrl}}/orders/4002

###
GET {{baseUrl}}/orders/1007
###

PUT {{baseUrl}}/orders/1006
Content-Type: application/json

{
  "OrderNumber": 1006,
  "CustomerName": "Order 99",
  "ProductName": "Order 99 description",
  "Quantity": 99
}
###


